apiVersion: v1
kind: Pod
metadata:
  name: dokuwiki-pod
  labels:
    function: app
spec:
  containers:
  - name: dokuwiki-container
    image: bitnami/dokuwiki:latest
    ports:
    - containerPort: 8080
    resources:
      requests:
        cpu: 250m 
        memory: 512Mi
        ephemeral-storage: 10Mi
      limits:
        cpu: 250m 
        memory: 512Mi
        ephemeral-storage: 10Mi
  - name: SITE_NAME
    value: "*"